fix: fix failure due to bootstrap due to ordering
As seen on a new machine where I tried to run:

    $ bin/git-cipher unlock                                                                                                                                     2.33s [main●] ~/code/wincent

`yarn` hasn't run, so it tries to run that, but running yarn fails if we
haven't installed the right node version previously:

    [error]   No artifact at /Users/wincent/code/wincent/vendor/git-cipher/bin/../node_modules/.yarn-integrity; did you forget to `yarn`? (running now)

      Error: '18.7.0' (18.7.0) not in downloads cache

So, swap the order, and we see the install happening first, then we
proceed from there:

    [info]    Installing NodeJS 18.7.0
      installing : node-v18.7.0
           mkdir : /Users/wincent/code/wincent/vendor/git-cipher/bin/../vendor/node/n/versions/node/18.7.0
           fetch : https://nodejs.org/dist/v18.7.0/node-v18.7.0-darwin-x64.tar.xz
         copying : node/18.7.0
       installed : v18.7.0 to /Users/wincent/code/wincent/vendor/git-cipher/bin/../vendor/node/bin/node
          active : v18.0.0 at /Users/wincent/n/bin/node