fix: export N_PREFIX
This fixes an issue where the program would fail with the following error:

```
[info]    Installing NodeJS 18.7.0
  installing : node-v18.7.0
       mkdir : /usr/local/n/versions/node/18.7.0
mkdir: /usr/local/n: Permission denied

  Error: sudo required (or change ownership, or define N_PREFIX)

zsh: exit 1
```

After the change `echo $N_PREFIX` still produces an empty line so we are not overwriting the users environment after the program exits.