style: pacify type-checker
    src/parseOptions.mts:8:1 - error TS6133: 'argv' is declared but its value is never read.

    8 import {argv} from 'node:process';
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~