fix: tell `n` to download automatically if needed
Because it's not in the downloads cache on CI:

    Run bin/yarn install --frozen-lockfile
           found : /home/runner/work/git-cipher/git-cipher/.node-version
            read : 22.18.0

    Error: 'auto' (22.18.0) not in downloads cache

- https://github.com/wincent/git-cipher/actions/runs/16697776243/job/47264391682